export const customerData = [
  {
    id: "CUS-001",
    client_name: "Green Valley Apartments",
    contact_person_name: "John Doe",
    waste_collection_type: "Solid Waste",
    recycling_type: "Plastic, Paper",
    provided_bin_sizes: "240L, 660L",
    bin_qty: 12,
    pickup_request_frequency: "Daily",
    assigned_driver_name: "Michael Smith",
    assigned_vehicle_no: "GV-1234",
    latitude: 6.5244,
    longitude: 3.3792,
    gps_address: "123 Green Ave, Ikeja, Lagos",
    remark: "Regular pickup at 6 AM",
    property_type: "Residential",
    property_subtype: "Apartment Complex",
    status: "Active",
    kyc_date: "2024-01-15",
    last_service_date: "2024-05-14",
    property_image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "CUS-002",
    client_name: "Oceanic Mall",
    contact_person_name: "Sarah Johnson",
    waste_collection_type: "Mixed Waste",
    recycling_type: "Metal, Glass",
    provided_bin_sizes: "1100L",
    bin_qty: 5,
    pickup_request_frequency: "Bi-weekly",
    assigned_driver_name: "David Wilson",
    assigned_vehicle_no: "OM-5678",
    latitude: 6.4281,
    longitude: 3.4219,
    gps_address: "45 Ocean Dr, Victoria Island, Lagos",
    remark: "Needs extra bins for events",
    property_type: "Commercial",
    property_subtype: "Shopping Mall",
    status: "Active",
    kyc_date: "2023-11-20",
    last_service_date: "2024-05-13",
    property_image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "CUS-003",
    client_name: "Tech Hub Office",
    contact_person_name: "Robert Brown",
    waste_collection_type: "E-Waste",
    recycling_type: "Electronics",
    provided_bin_sizes: "120L",
    bin_qty: 3,
    pickup_request_frequency: "Monthly",
    assigned_driver_name: "Kevin Adams",
    assigned_vehicle_no: "TH-9012",
    latitude: 6.4474,
    longitude: 3.4723,
    gps_address: "88 Innovation Way, Lekki, Lagos",
    remark: "Call before arrival",
    property_type: "Commercial",
    property_subtype: "Office Building",
    status: "Pending",
    kyc_date: "2024-03-05",
    last_service_date: "2024-04-28",
    property_image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "CUS-004",
    client_name: "Sunrise Hospital",
    contact_person_name: "Dr. Emily White",
    waste_collection_type: "Medical Waste",
    recycling_type: "None",
    provided_bin_sizes: "240L (Biohazard)",
    bin_qty: 8,
    pickup_request_frequency: "Daily",
    assigned_driver_name: "James Miller",
    assigned_vehicle_no: "SH-3456",
    latitude: 6.5050,
    longitude: 3.3614,
    gps_address: "12 Medical Rd, Surulere, Lagos",
    remark: "Strict biohazard protocols",
    property_type: "Institutional",
    property_subtype: "Hospital",
    status: "Active",
    kyc_date: "2023-09-12",
    last_service_date: "2024-05-15",
    property_image: "https://images.unsplash.com/photo-1587351591046-aa3605af8851?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "CUS-005",
    client_name: "Grand Hotel",
    contact_person_name: "Alex Turner",
    waste_collection_type: "Food Waste",
    recycling_type: "Compostable",
    provided_bin_sizes: "660L",
    bin_qty: 10,
    pickup_request_frequency: "Daily",
    assigned_driver_name: "Michael Smith",
    assigned_vehicle_no: "GV-1234",
    latitude: 6.4311,
    longitude: 3.4158,
    gps_address: "10 Luxury Ln, Victoria Island, Lagos",
    remark: "Rear entrance access",
    property_type: "Hospitality",
    property_subtype: "Hotel",
    status: "Active",
    kyc_date: "2024-02-10",
    last_service_date: "2024-05-14",
    property_image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=400",
  }
];

export const dashboardStats = [
  { label: "Total Customers", value: "1,248", change: "+12%", trend: "up" },
  { label: "Active Drivers", value: "42", change: "+3", trend: "up" },
  { label: "Active Collections", value: "856", change: "+5.4%", trend: "up" },
  { label: "Daily Pickups", value: "124", change: "-2%", trend: "down" },
  { label: "Assigned Vehicles", value: "38", change: "0%", trend: "neutral" },
  { label: "Pending Assignments", value: "14", change: "-5", trend: "up" },
];
