export const CUSTOMERS_DATA = [
  {
    id: "CUS-001",
    client_name: "Green Valley Apartments",
    contact_person_name: "John Doe",
    waste_collection_type: "Solid Waste",
    recycling_type: "Paper & Plastic",
    provided_bin_sizes: "240L",
    bin_qty: 12,
    pickup_request_frequency: "Daily",
    assigned_driver_name: "Robert Smith",
    assigned_vehicle_no: "GV-2024-01",
    latitude: 28.6139,
    longitude: 77.209,
    gps_address: "Sector 15, Green Valley, New Delhi",
    remark: "Morning pickup preferred",
    property_type: "Residential",
    property_subtype: "Apartment Complex",
    status: "Active",
    kyc_date: "2024-01-15",
    service_date: "2024-05-15",
  },
  {
    id: "CUS-002",
    client_name: "Tech Park Plaza",
    contact_person_name: "Jane Smith",
    waste_collection_type: "E-Waste",
    recycling_type: "Electronic Components",
    provided_bin_sizes: "120L",
    bin_qty: 5,
    pickup_request_frequency: "Weekly",
    assigned_driver_name: "Michael Brown",
    assigned_vehicle_no: "TP-2024-05",
    latitude: 28.625,
    longitude: 77.215,
    gps_address: "Cyber City, Phase 2, Gurugram",
    remark: "Sensitive materials, handle with care",
    property_type: "Commercial",
    property_subtype: "IT Park",
    status: "Active",
    kyc_date: "2024-02-10",
    service_date: "2024-05-14",
  },
  {
    id: "CUS-003",
    client_name: "City Hospital",
    contact_person_name: "Dr. Sarah Wilson",
    waste_collection_type: "Bio-Medical",
    recycling_type: "Non-Hazardous",
    provided_bin_sizes: "60L",
    bin_qty: 20,
    pickup_request_frequency: "Bi-Daily",
    assigned_driver_name: "David Miller",
    assigned_vehicle_no: "CH-2024-09",
    latitude: 28.59,
    longitude: 77.23,
    gps_address: "Main Road, Medical District, Delhi",
    remark: "Strict adherence to safety protocols required",
    property_type: "Institutional",
    property_subtype: "Hospital",
    status: "Pending",
    kyc_date: "2024-03-05",
    service_date: "2024-05-15",
  },
  {
    id: "CUS-004",
    client_name: "Sunshine School",
    contact_person_name: "Mark Johnson",
    waste_collection_type: "Organic Waste",
    recycling_type: "Compostable",
    provided_bin_sizes: "240L",
    bin_qty: 8,
    pickup_request_frequency: "Daily",
    assigned_driver_name: "Robert Smith",
    assigned_vehicle_no: "GV-2024-01",
    latitude: 28.63,
    longitude: 77.25,
    gps_address: "Education Hub, Sector 4, Noida",
    remark: "Pick up before school hours",
    property_type: "Institutional",
    property_subtype: "School",
    status: "Active",
    kyc_date: "2024-01-20",
    service_date: "2024-05-15",
  },
  {
    id: "CUS-005",
    client_name: "Metro Mall",
    contact_person_name: "Alice Cooper",
    waste_collection_type: "Solid Waste",
    recycling_type: "Mixed Recyclables",
    provided_bin_sizes: "660L",
    bin_qty: 4,
    pickup_request_frequency: "Daily",
    assigned_driver_name: "Michael Brown",
    assigned_vehicle_no: "TP-2024-05",
    latitude: 28.55,
    longitude: 77.18,
    gps_address: "City Center, South Delhi",
    remark: "Night pickup only",
    property_type: "Commercial",
    property_subtype: "Shopping Mall",
    status: "Active",
    kyc_date: "2024-02-25",
    service_date: "2024-05-15",
  },
];

export const DASHBOARD_STATS = {
  totalCustomers: 1240,
  activeDrivers: 45,
  activeCollections: 182,
  dailyPickups: 342,
  assignedVehicles: 38,
  pendingAssignments: 12,
};
